### ISSUE TITLE
create/edit order page

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/pos-system-pizzabois#19]

**Comment by JoeyEbach** [comment]
Users should have the ability to create new orders and edit orders.

This will require:
- [ ]  Creating a Post fetch call to push a new order object payload to Firebase
- [ ]  Creating a Patch fetch call to update an order in Firebase with the updated object payload
- [ ]  Rendering a create/edit form to the dom #18 
- [ ]  A submit event listener that gathers the payload information and runs the fetch calls upon submit
