### ISSUE TITLE
go to payment button

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/pos-system-pizzabois#20]

**Comment by JoeyEbach** [comment]
After an order has been created, the user should have the ability to click a button and go to the payment page. 

This will require: 
- [ ] Rendering a Go To Payment button to the dom on the View Order page 
- [ ] A click addEventLister on the Go To Payment button that brings up the Payment page
- [ ] Dynamically rendering a Payment form page to the dom with inputs to enter the payment information
- [ ] A Get fetch call to grab a single order from Firebase 
- [ ] A Post fetch call that pushes the payment object data (payload) to Firebase
- [ ] A submit addEventListener that gathers the payment input payload and pushes the payment information to Firebase via the fetch call
